#!/usr/bin/env python3
"""Generate contract artifacts or reject drift without changing the checkout."""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pydantic.json_schema import models_json_schema  # noqa: E402

from contracts.http import OPERATIONS  # noqa: E402
from contracts.models import PUBLIC_MODELS, RESERVED_MODELS  # noqa: E402

NOTICE = (
    "GENERATED by scripts/generate-contracts.py; edit contracts/models.py or contracts/http.py."
)


def ref(name):
    return {"$ref": f"#/components/schemas/{name}"}


def generate_json():
    all_models = PUBLIC_MODELS + RESERVED_MODELS
    _, combined = models_json_schema(
        [(model, "validation") for model in all_models],
        ref_template="#/components/schemas/{model}",
    )
    headers = {
        "X-Request-ID": {
            "description": "Server request identifier",
            "schema": {"type": "string", "format": "uuid"},
        },
        "Cache-Control": {"schema": {"type": "string", "const": "no-store"}},
    }
    paths = {}
    for op in OPERATIONS:
        parameters = [
            {
                "name": name,
                "in": "path",
                "required": True,
                "schema": {"type": "string", "format": "uuid"},
            }
            for name in re.findall(r"\{([^}]+)\}", op.path)
        ]
        if op.paginated:
            parameters.extend(
                [
                    {
                        "name": "limit",
                        "in": "query",
                        "schema": {"type": "integer", "minimum": 1, "maximum": 100, "default": 50},
                    },
                    {
                        "name": "cursor",
                        "in": "query",
                        "schema": {"type": "string", "minLength": 1, "maxLength": 2048},
                    },
                ]
            )
        if op.request:
            parameters.append(
                {
                    "name": "X-CSRF-Token",
                    "in": "header",
                    "required": True,
                    "schema": {"type": "string", "minLength": 32, "maxLength": 256},
                }
            )
        success_headers = dict(headers)
        if op.success == 201:
            success_headers["Location"] = {
                "description": "Relative API URL of created resource",
                "schema": {"type": "string"},
            }
        responses = {
            str(op.success): {
                "description": "Success",
                "headers": success_headers,
                "content": {"application/json": {"schema": ref(op.response.__name__)}},
            }
        }
        for status, code in [
            (401, "unauthenticated"),
            (403, "forbidden"),
            (404, "not_found"),
            (409, "conflict"),
            (413, "payload_too_large"),
            (422, "invalid_input"),
            (429, "rate_limited"),
            (500, "internal_error"),
            (503, "dependency_unavailable"),
        ]:
            error_headers = dict(headers)
            if status in (429, 503):
                error_headers["Retry-After"] = {
                    "description": "Required when retryable; delay in seconds",
                    "schema": {"type": "integer", "minimum": 1},
                }
            responses[str(status)] = {
                "description": code,
                "headers": error_headers,
                "content": {"application/json": {"schema": ref("Error")}},
            }
        operation = {
            "operationId": op.operation_id,
            "summary": op.summary,
            "parameters": parameters,
            "responses": responses,
        }
        if op.request:
            operation["requestBody"] = {
                "required": True,
                "content": {"application/json": {"schema": ref(op.request.__name__)}},
            }
        paths.setdefault("/api/v1" + op.path, {})[op.method] = operation
    document = {
        "openapi": "3.1.0",
        "info": {
            "title": "Kanior foundation contract",
            "version": "0.1.0",
            "description": NOTICE + " Design contract only; endpoints are not yet implemented. "
            "Reserved components are not public routes.",
        },
        "security": [{"sessionCookie": []}],
        "paths": paths,
        "components": {
            "securitySchemes": {
                "sessionCookie": {"type": "apiKey", "in": "cookie", "name": "kanior_session"}
            },
            "schemas": combined["$defs"],
        },
    }
    artifacts = {"schemas/openapi/foundation-v1.json": document}
    locations = [
        "schemas/imports/transcript-v1.schema.json",
        "schemas/ai/evidence-selection-v1.schema.json",
        "schemas/ai/evidence-span-selection-v1.schema.json",
        "schemas/events/access-changed-v1.schema.json",
        "schemas/events/transcript-published-v1.schema.json",
    ]
    for model, path in zip(RESERVED_MODELS, locations, strict=True):
        artifacts[path] = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$comment": NOTICE,
            **model.model_json_schema(),
        }
    return artifacts


def generate(destination):
    for relative, document in generate_json().items():
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            json.dumps(document, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    node = shutil.which("node")
    cli = ROOT / "tools/contracts/node_modules/openapi-typescript/bin/cli.js"
    if not node or not cli.is_file():
        raise SystemExit(
            "Install Node and run npm ci --prefix tools/contracts before generation/check."
        )
    output = destination / "contracts/generated/api.d.ts"
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            node,
            str(cli),
            str(destination / "schemas/openapi/foundation-v1.json"),
            "--output",
            str(output),
        ],
        check=True,
        cwd=ROOT,
    )
    # Normalize line endings for deterministic cross-platform comparisons.
    output.write_text(output.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
    compiler = ROOT / "tools/contracts/node_modules/typescript/bin/tsc"
    subprocess.run(
        [node, str(compiler), "--noEmit", "--strict", "--lib", "es2022,dom", str(output)],
        check=True,
        cwd=ROOT,
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not args.check:
        generate(ROOT)
        return 0
    with tempfile.TemporaryDirectory(prefix="kanior-contracts-") as directory:
        temp = Path(directory)
        generate(temp)
        expected = {p.relative_to(temp) for p in temp.rglob("*") if p.is_file()}
        actual = {p.relative_to(ROOT) for p in (ROOT / "schemas").rglob("*.json")}
        actual |= {p.relative_to(ROOT) for p in (ROOT / "contracts/generated").rglob("*.ts")}
        failures = [
            str(p)
            for p in sorted(expected | actual)
            if p not in expected
            or not (ROOT / p).is_file()
            or (ROOT / p).read_bytes() != (temp / p).read_bytes()
        ]
        if failures:
            print("Generated contract drift: " + ", ".join(failures), file=sys.stderr)
            return 1
    print("Generated contract drift and TypeScript checks: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
